version: '2'
services:
  soethbyshipping-app:
    image: soethbyshipping
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://soethbyshipping-postgresql:5432/soethbyShipping
      - JHIPSTER_CACHE_REDIS_SERVER=redis://soethbyshipping-redis:6379
      - JHIPSTER_CACHE_REDIS_CLUSTER=false
      # - JHIPSTER_CACHE_REDIS_SERVER=redis://soethbyshipping-redis:6379
      # - JHIPSTER_CACHE_REDIS_CLUSTER=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  soethbyshipping-postgresql:
    extends:
      file: postgresql.yml
      service: soethbyshipping-postgresql
  soethbyshipping-redis:
    extends:
      file: redis.yml
      service: soethbyshipping-redis
